<?php

namespace App\Service;

use App\Entity\Emission;
use App\Entity\ProgrammationRuleSlot;
use App\Entity\User;
use App\Repository\UserRepository;
use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\ThemeRepository;
use App\Entity\Theme;
use App\Entity\Editeur;
use App\Repository\EditeurRepository;

class LiveEmissionCreator
{
    public function __construct(
        private readonly EntityManagerInterface $em,
        private readonly Connection $connection,
        private readonly UserRepository $userRepository,
        private readonly ThemeRepository $themeRepository,
        private readonly EditeurRepository $editeurRepository,
    ) {}

    public function createFromSlot(ProgrammationRuleSlot $slot, \DateTimeInterface $startsAt): Emission
{
    $rule = $slot->getRule();

    if ($rule === null) {
        throw new \RuntimeException('Impossible de créer un direct : ce créneau n’est lié à aucune règle.');
    }

    $category = $rule->getCategory();

    if ($category === null) {
        throw new \RuntimeException('Impossible de créer un direct : la règle n’a pas de catégorie.');
    }

    $users = $this->findUsersForCategory((int) $category->getId());

    $theme = $this->themeRepository->find(15);

    if (!$theme instanceof Theme) {
        throw new \RuntimeException('Thème par défaut introuvable.');
    }

    $editeur = null;
    $editeurId = $category->getEditeur();

    if ($editeurId !== null) {
        $editeur = $this->editeurRepository->find($editeurId);

        if (!$editeur instanceof Editeur) {
            throw new \RuntimeException(sprintf('Éditeur introuvable pour l’ID %d.', $editeurId));
        }
    }

    $emission = new Emission();

    $emission
        ->setTitre($this->buildTitle($category->getTitre(), $startsAt))
        ->setKeyword('')
        ->setDatepub(\DateTime::createFromInterface($startsAt))
        ->setRef('')
        ->setDuree($slot->getDurationMinutes() ?? 15)
        ->setUrl(null)
        ->setDescriptif($this->buildDescription($category->getTitre(), $startsAt))
        ->setCategorie($category)
        ->setTheme($theme)
        ->setEditeur($editeur)
        ->setAutoGeneratedForSlot($slot)
        ->setAutoGeneratedForStartsAt(\DateTime::createFromInterface($startsAt))
        ->markAsAutoGenerated();

    foreach ($users as $user) {
        $emission->addUser($user);
    }

    $this->em->persist($emission);
    $this->em->flush();

    return $emission;
}

    /**
     * @return User[]
     */
    private function findUsersForCategory(int $categoryId): array
    {
        $rows = $this->connection->fetchAllAssociative(
            'SELECT user_id FROM categories_user WHERE categories_id = :categoryId',
            ['categoryId' => $categoryId]
        );

        $userIds = [];

        foreach ($rows as $row) {
            if (isset($row['user_id'])) {
                $userIds[] = (int) $row['user_id'];
            }
        }

        $userIds = array_values(array_unique($userIds));

        if ($userIds === []) {
            return [];
        }

        /** @var User[] $users */
        $users = $this->userRepository->findBy(['id' => $userIds]);

        return $users;
    }

    private function buildTitle(string $categoryTitle, \DateTimeInterface $startsAt): string
    {
        return sprintf(
            'Direct du %s - %s',
            $startsAt->format('d/m/Y'),
            $categoryTitle
        );
    }

    private function buildDescription(string $categoryTitle, \DateTimeInterface $startsAt): string
    {
        return sprintf(
            "Émission en direct du %s à %s, générée automatiquement depuis la grille de programmation pour la catégorie « %s ».\n\nCette fiche doit être complétée après l’émission.",
            $startsAt->format('d/m/Y'),
            $startsAt->format('H:i'),
            $categoryTitle
        );
    }
}
