services:
  app:
    build:
      context: .
      dockerfile: dockerfile.prod
    container_name: sitezinzine_app_prod
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://user:password@db:3306/symfony?serverVersion=8.0
    depends_on:
      - db
    volumes:
      - ./public/uploads/images:/var/www/html/public/uploads/images
      - ./public/uploads/emissionsMp3:/var/www/html/public/uploads/emissionsMp3
    ports:
      - "8080:80"
    networks:
      - symfony_network

  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - sitezinzine_db_data:/var/lib/mysql
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"  # on évite le port 80 ici aussi
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100M
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - symfony_network

volumes:
  sitezinzine_db_data:
    external: true

networks:
  symfony_network:
    driver: bridge
