# 🧱 STAGE 1 : build avec Composer
FROM composer:2 as composer_build

WORKDIR /app

# Copie les fichiers nécessaires pour l'installation
COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader

# 🏁 STAGE 2 : image de production
FROM php:8.3-apache

# Dépendances système + extensions PHP
RUN apt-get update && apt-get install -y \
    libicu-dev zip git unzip libzip-dev && \
    docker-php-ext-install intl pdo pdo_mysql zip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Active mod_rewrite
RUN a2enmod rewrite

# Crée un utilisateur non-root
RUN addgroup --system app && adduser --system --ingroup app appuser

# Définir le dossier de travail
WORKDIR /var/www/html

# Copie du code source (tout sauf /vendor)
COPY . .

# Copie du dossier /vendor depuis le premier stage
COPY --from=composer_build /app/vendor ./vendor

# Copie du script d'entrée
COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Droits
RUN chown -R appuser:app /var/www/html

USER appuser


ENTRYPOINT ["entrypoint.sh"]

CMD ["apache2-foreground"]
