services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: symfony_app
    working_dir: /var/www/html
    platform: linux/amd64
    ports:
      - "8080:80"  # redirige vers 8080 pour éviter le conflit avec Nginx
    depends_on:
      - db
    networks:
      - symfony_network
    volumes:
      - .:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
    env_file:
      - .env

  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - sitezinzine_db_data:/var/lib/mysql
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"  # on évite le port 80 ici aussi
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100M
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - symfony_network

volumes:
  sitezinzine_db_data:
    external: true

networks:
  symfony_network:
    driver: bridge
