# Utilisation de l'image officielle PHP avec Apache
FROM php:8.2-apache

# Installation des extensions PHP nécessaires
# Installation des dépendances système et extensions PHP
RUN apt-get update && apt-get install -y \
    libpq-dev \
    unzip \
    git \
    libicu-dev \
    && docker-php-ext-install \
        pdo \
        pdo_mysql \
        intl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


# Activation des modules Apache
RUN a2enmod rewrite

# Installation de Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Configuration PHP pour intl
RUN echo "extension=intl.so" > /usr/local/etc/php/conf.d/docker-php-ext-intl.ini


# Copie des fichiers du projet
COPY . /var/www/html

# Configuration Apache
COPY apache.conf /etc/apache2/sites-available/000-default.conf

# Définition du répertoire de travail
WORKDIR /var/www/html

# Attribution des droits nécessaires
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Exposition du port 80
EXPOSE 80
