services:
  app:
    build:
      context: .
      dockerfile: dockerfile.prod
    container_name: sitezinzine_app_prod
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://user:password@symfony_db:3306/symfony?serverVersion=8.0
    depends_on:
      - db
    volumes:
      - ./public/uploads/images:/var/www/html/public/uploads/images
      - ./public/uploads/emissionsMp3:/var/www/html/public/uploads/emissionsMp3
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: