services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: symfony_app
    working_dir: /var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - symfony_network
    volumes:
      - .:/var/www/html           # ⬅️ Monter tout le projet Symfony
      - ./public/uploads:/var/www/html/public/uploads  # ⬅️ Toujours garder ça pour les uploads
    env_file:
      - .env.prod
  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - sitezinzine_db_data:/var/lib/mysql
    networks:
      - symfony_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100M
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - symfony_network

volumes:
  sitezinzine_db_data:
    external: true

networks:
  symfony_network:
    driver: bridge


