services:
  app:
    build: .
    container_name: symfony_app
    working_dir: /var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - symfony_network
    volumes:
      - ./public/uploads:/var/www/html/public/uploads  # ⬅️ Volume pour les fichiers uploadés
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      APP_SECRET: "9021d87b778fec23df9779345aca92f"  # ⬅️ À remplacer par un vrai secret
      DATABASE_URL: "mysql://user:password@symfony_db:3306/symfony?serverVersion=8.0"
      MAILER_DSN: "doctrine://default?auto_setup=0"  # ⬅️ À adapter si tu utilises un vrai mailer
      # Ajoute d'autres variables si besoin

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100M
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge
