vich_uploader:
    db_driver: orm

    mappings:
        emissions:
            uri_prefix: /images/emissions
            upload_destination: '%kernel.project_dir%/public/images/emissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
