vich_uploader:
    db_driver: orm

    mappings:
        emissions:
            uri_prefix: /images/emissions
            upload_destination: '%kernel.project_dir%/public/images/emissions'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'titre' }
        categories:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'titre' }
        themes:
            uri_prefix: /images/theme
            upload_destination: '%kernel.project_dir%/public/images/theme'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'name'} 
        annonces:
            uri_prefix: /images/annonce
            upload_destination: '%kernel.project_dir%/public/images/annonce'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'titre'}     
        emissionsMp3:
                    uri_prefix: /emissionsMp3
                    upload_destination: '%kernel.project_dir%/public/emissionsMp3'
                    namer:
                        service: Vich\UploaderBundle\Naming\PropertyNamer
                        options: { property: 'titre' }