name: 🚀 Publish Docker image to GHCR on tag

on:
  push:
    tags:
      - 'v*.*.*' # Déclenchement sur les tags de type v1.0.0, v1.0.1, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Nécessaire pour pousser sur GHCR

    steps:
      - name: 🔍 Checkout repository
        uses: actions/checkout@v4

      - name: 🔐 Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏷️ Extract tag name
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: 🛠️ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./sitezinzine
          file: ./sitezinzine/dockerfile.prod
          push: true
          tags: |
            ghcr.io/eloisemcglasson/sitezinzine-app:${{ env.TAG }}
            ghcr.io/eloisemcglasson/sitezinzine-app:latest

